---
# Environment variables: https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
branches:
  # Safelist
  only:
    - feature/travis-build-integration
git:
  depth: 1
matrix:
  include:
    -
      # Including OSX later will allow us to run a Build Matrix.
      os: linux
      sudo: false
      # Source: https://docs.travis-ci.com/user/languages/android/
      language: android
      android:
        # If components are missing on build, do `android list sdk --no-ui --all --extended`
        # in local dev environment to find out what's missing.
        components:
          # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
          # See: https://docs.travis-ci.com/user/languages/android/#Installing-a-newer-SDK-Platform-Tools-revision
          - tools
          - platform-tools
          - tools

          # The BuildTools version used by your project
          - build-tools-26.0.2

          # The SDK version used to compile your project
          - android-26

          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-26

          # Specify at least one system image,
          # if you need to run emulator(s) during your tests
          - sys-img-armeabi-v7a-android-26
          - sys-img-armeabi-v7a-android-17

          # Install Android SDK components.
          - sys-img-armeabi-v7a-android-tv-l
          - add-on
          - extra
  addons:
    apt:
      sources:
        - 
          sourceline: "deb https://dl.yarnpkg.com/debian/ stable main"
          key_url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
      packages:
        - oracle-java8-installer
        - oracle-java8-set-default
        - yarn
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_cache:
  - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
  - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.cache/yarn
before_install:
  - "export LANG=en_US.UTF-8"
  # v8 is the active LTS release.
  - "nvm install 8"
  - "yarn global add ionic cordova"
script:
  # Run tests here.
  - "echo \"Travis branch is $TRAVIS_BRANCH\""
  - "echo \"Travis branch is in pull request $TRAVIS_PULL_REQUEST\""
  - ./travis/build/run.sh
after_failure:
  - "echo \"[FAIL] Build result is $TRAVIS_TEST_RESULT\""
after_success:
  - "echo \"[PASS] Build result is $TRAVIS_TEST_RESULT\""
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - JRE_HOME=/usr/lib/jvm/java-8-oracle/jre
    - S3_BUCKET="041440807701-us-west-2-device-farm"
    - ANDROID_BUILD_DIR="${TRAVIS_BUILD_DIR}/platforms/android/build/outputs/apk/debug"
    - ANDROID_DEBUG_APK_NAME="android-debug-${TRAVIS_BUILD_NUMBER}-${TRAVIS_BUILD_ID}.apk"
    - ANDROID_BUILD_LATEST_DIR="${ANDROID_BUILD_DIR}"/latest
    # AWS_ACCESS_KEY_ID
    - secure: "BHBfYN2zt0pTk3NYl0+/BREPq6FcAgE03XeoVy3mmwb86YqeFgKWf89ErOJdjVCmCC/1z/fN5nlcS+e/gFKVFCm01pYHMYOyFpvbWVzz/RpWNU273FN2PItNyrhAVf/hIOHcdZYMiXlizaUJe7tPggXfFEFoWpTJGVsPYFpYHt+YAtUeQjx3Io8fDVVrIGIkXwO7uAn8m2sy/nb8npfK3GMTLrGyIVcw9YRK5px1HP1yoEl2/Bm2vnz0L8WSJEvt50m0ftGt9fbxBt5MQXC98BIc3yP8iwRI6LVnI7cnh9WgLWhOvrSH3OuTNvHzb5eLqQkfemsRr+vajb+eJH5fYqNHAM29YCDBO0AFBX8g2Uif58cm3YqJNvs/D3cwyQEWDZsNM/6TevwXlJ651GyJYcqNSZeoQESZkzrGGSs0DZ4xLhGqhCiaKdsUB7e6KBBJXE+ddVotCS1GXUYBHxoMMWc24Oexb3x3mM+jS4V1eepm52pzQzEk/61PeBOOtQCBYEZriTfVT4nitanK7zGy2ctnmwtkGihze63xir/RajsM6wcIsazH0mRQG2SgtX4aeGXDTRMmhXw4bF+BYVU+qHAfz35F8xreYJ4i6fx0YI3OVtCTZcoZHGvff2p0l/QC7MCkE7Wn5YIAhD8IIKKaWcsWVLdSx56gLCMdZlF4aH4="
    # AWS_SECRET_ACCESS_KEY
    - secure: "pmiFSEAzwAWkIUd6l1Q8xCpqrOhPXHWqirmIJUP7VBO0xxCDZqpsLtrW3mDceA3ureoqHfMdvZ0FBCYNgao3zgtUys/dVlQTpaAQOQHd1M0U+SHTiVIjICVvCNW0Gr7Y/uhAi6klpMC2PGCbn111rIoeJKn3dSlT+QFDEHN1BBZ2Hlt6b3EZ42KJwrpgxm41RDaZyclQBgysxrlLaAF9g4+ozlJt7cg/FAD326KAmhBRpTEKV08bXCGvOx94tJOjecPmJC/VWh7xNWC5M1HL60T6uA4fTJ3/oPuYkSWwKeQQuQo5fvMowoX5KGqVaNc//I+g4jZdOR5ncdmQJJTQq4MgQKAjWGRRbBAPXaSIboDTlUL57tgL+cHFMA9D6W/k0zDlPdsB7d9X0yS3qalD+U0lxLEmx5uRakCOd2hhOZvrjWg8eomQvfQ/e9Zda6sqLbP3rF3QRrE4ePC/ZFcP1glIMH46fyen/zC2RcaQ/eelNRhwn6hHCI3BEqyWyaqwKMypLC9+ZbZZip/Fi3aoB4PCxxbC6C+Yh7j0U1zuSSRIP1qyjFtizHSPXz4DSLgtz3V57gJ5hDEUXCVoceX+uJH6iRo4wK8Fj+sAZ/ntq54qnntlrB5+fAp+nbR84e+4a3p+4S/WfX4hBESgIxfmH+3SjTUvZx11Mowad0ZFAbw="
before_deploy:
  - ./travis/deploy/before/prepare.sh
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  skip_cleanup: true
  bucket: "${S3_BUCKET}"
  local_dir: "${ANDROID_BUILD_LATEST_DIR}"
  on:
    all_branches: true
# after_deploy:
#   - ./travis/deploy/after/run_tests.sh
#   - ./travis/deploy/after/check_results.sh